inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.4
  Excludes:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 3

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/views/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*'

#TODO: ちょっとめんどくさいので
Rails/I18nLocaleTexts:
  Enabled: false